"""initial migration

Revision ID: 30cd90db667f
Revises: None
Create Date: 2015-09-15 13:32:23.436194

"""

# revision identifiers, used by Alembic.
revision = '30cd90db667f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appname', sa.Text(), nullable=True),
    sa.Column('urltext', sa.Text(), nullable=True),
    sa.Column('status_code', sa.String(length=64), nullable=True),
    sa.Column('lastchecked', sa.DateTime(), nullable=True),
    sa.Column('resplength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urls_appname'), 'urls', ['appname'], unique=False)
    op.create_index(op.f('ix_urls_urltext'), 'urls', ['urltext'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_urls_urltext'), table_name='urls')
    op.drop_index(op.f('ix_urls_appname'), table_name='urls')
    op.drop_table('urls')
    op.drop_table('roles')
    ### end Alembic commands ###
